### ISSUE TITLE
Error with utils/dist not being accessible

### ISSUE THREAD

**Issue by henri-ly** [cardano-foundation/ledgerjs-hw-app-cardano#36]
Hello,

We are trying to make ledger-live work with version 6.0.0 but it's seems that we have some issues with some function that we are using in 5.x

```
error TS2614: Module '"@cardano-foundation/ledgerjs-hw-app-cardano/dist/utils"' has no exported member 'str_to_path'. Did you mean to use 'import str_to_path from "@cardano-foundation/ledgerjs-hw-app-cardano/dist/utils"' instead?
```
We can't use for some reason str_to_path from utils.

Example :

```
import { str_to_path } from "@cardano-foundation/ledgerjs-hw-app-cardano/dist/utils";

const path = "" //well it will not working but it's just to illustrate that we can't import str_to_path anymore
str_to_path(path)
```

Thank you very much !

**Comment by janmazak** [comment]
The function was refactored into another file:
https://github.com/vacuumlabs/ledgerjs-cardano-shelley/blob/5e83052fd02c8e3bf88dbc837bb9219d80b41a40/src/utils/address.ts#L27
You just need to change the import path to `@cardano-foundation/ledgerjs-hw-app-cardano/dist/utils/address`. Sorry for the inconvenience.

**Comment by henri-ly** [comment]
That's work perfectly !

Sorry for disturbing.

Thank you 👍
